# training parameters
epochs: 30
limit_train_batches:
limit_val_batches:
limit_test_batches:
learning_rate: 0.0001
batch_size: 32
num_workers: 8
pin_memory: True
score_average: 'micro'
train_val_test_split: [0.7, 0.15, 0.15]
seed: 42
dataloader_timeout: 600

# paths
work_dir: 'C:/CODE/master-thesis'
example_data_path: 'output/test_data'
example_image_output: 'figures/transform_examples'


# dataset parameters
datasets:
  bigearthnet:
    task: multilabel
    input_channels: 12
    image_size: 120
    num_labels: 19
    epochs: 30
  rgb_bigearthnet:
    task: multilabel
    input_channels: 3
    image_size: 120
    num_labels: 19
    epochs: 30
  imagenet:
    task: multiclass
    input_channels: 3
    path: /media/storagecube/data/shared/datasets/ImageNet-2012
    image_size: 224
    num_classes: 1000
    epochs: 30
  caltech:
    task: multiclass
    input_channels: 3
    image_size: 224
    top_n: 20
    num_classes: 20  # manually set
    path: /media/storagecube/data/shared/datasets/Caltech101
    epochs: 30
  caltech_ft:
    task: multiclass
    input_channels: 3
    image_size: 224
    top_n: 20
    num_classes: 20  # manually set
    path: /media/storagecube/data/shared/datasets/Caltech101
    epochs: 30
  caltech_120:
    task: multiclass
    input_channels: 3
    image_size: 120
    top_n: 20
    num_classes: 20  # manually set
    path: /media/storagecube/data/shared/datasets/Caltech101
    epochs: 30
  deepglobe:
    task: multilabel
    input_channels: 3
    image_size: 120
    num_labels: 6
    path: /media/storagecube/data/shared/datasets/deepGlobe/ML_DeepGlobe/patches.lmdb
    labels_path: /media/storagecube/data/shared/datasets/deepGlobe/ML_DeepGlobe/labels.parquet
    csv_paths:
      train: /media/storagecube/data/shared/datasets/deepGlobe/splits/deepglobe_version2_train.csv
      validation: /media/storagecube/data/shared/datasets/deepGlobe/splits/deepglobe_version2_test.csv
      test: /media/storagecube/data/shared/datasets/deepGlobe/splits/deepglobe_version2_test.csv
    epochs: 30

