# training parameters
epochs: 5
limit_train_batches:
limit_val_batches:
limit_test_batches:
learning_rate: 0.001
batch_size: 32
num_workers: 40
pin_memory: True
score_average: 'micro'


# dataset parameters
datasets:
  bigearthnet:
    task: multilabel
    input_channels: 14
    image_size: 112
    num_classes:
    num_labels: 19
  imagenet:
    path: /media/storagecube/data/shared/datasets/ImageNet-2012
    task: multiclass
    input_channels: 3
    image_size: 224
    num_classes: 1000
    num_labels:
    train_val_test_split: [0.7, 0.15, 0.15]