# training parameters
epochs: 10
limit_train_batches:
limit_val_batches:
limit_test_batches:
learning_rate: 0.0001
batch_size: 32
num_workers: 6
pin_memory: True
score_average: 'micro'
train_val_test_split: [0.7, 0.15, 0.15]
seed: 42
dataloader_timeout: 600

# paths
output_dir: '/home/olivers/colab-master-thesis/output'
checkpoint_dir: '/media/storagecube/olivers/logs/checkpoints'
example_image: '/media/storagecube/data/shared/datasets/ImageNet-2012/n01440764/n01440764_10026.JPEG'
example_tensors:
  imagenet: '/home/olivers/colab-master-thesis/output/test_data/Imagenet_tensor.pt'
  bigearthnet: '/home/olivers/colab-master-thesis/output/test_data/BEN_tensor.pt'
example_BEN_tensor_unnormalized: '/home/olivers/colab-master-thesis/output/test_data/BEN_tensor_unnormalized.pt'
example_image_output: "/home/olivers/colab-master-thesis/output/transform_examples"


# dataset parameters
datasets:
  bigearthnet:
    task: multilabel
    input_channels: 12  # 14
    image_size: 128
    num_labels: 19
  imagenet:
    task: multiclass
    input_channels: 3
    path: /media/storagecube/data/shared/datasets/ImageNet-2012
    image_size: 224
    num_classes: 1000
  caltech:
    task: multiclass
    input_channels: 3
    image_size: 224
    num_classes: 102
    path: /media/storagecube/data/shared/datasets/Caltech101
  deepglobe:
    task: multilabel
    input_channels: 3
    image_size: 120
    num_labels: 6
    path: '/media/storagecube/data/shared/datasets/deepGlobe/ML_DeepGlobe/patches.lmdb'
    labels_path: '/media/storagecube/data/shared/datasets/deepGlobe/ML_DeepGlobe/labels.parquet'
    csv_paths:
      train: '/media/storagecube/data/shared/datasets/deepGlobe/splits/deepglobe_version2_train.csv'
      validation: '/media/storagecube/data/shared/datasets/deepGlobe/splits/deepglobe_version2_test.csv'
      test: '/media/storagecube/data/shared/datasets/deepGlobe/splits/deepglobe_version2_test.csv'

