BEN_LABELS = {
    0: {"original": "Urban fabric", "short": "Urban"},
    1: {"original": "Industrial or commercial units", "short": "Industrial Units"},
    2: {"original": "Arable land", "short": "Arable"},
    3: {"original": "Permanent crops", "short": "Crops"},
    4: {"original": "Pastures", "short": "Pastures"},
    5: {"original": "Complex cultivation patterns", "short": "Cultivation"},
    6: {
        "original": "Land principally occupied by agriculture, with significant areas of natural vegetation",
        "short": "Agriculture",
    },
    7: {"original": "Agro-forestry areas", "short": "Agro-forestry"},
    8: {"original": "Broad-leaved forest", "short": "Broad-leaved"},
    9: {"original": "Coniferous forest", "short": "Coniferous"},
    10: {"original": "Mixed forest", "short": "Mixed forest"},
    11: {"original": "Natural grassland and sparsely vegetated areas", "short": "Grassland"},
    12: {"original": "Moors, heathland and sclerophyllous vegetation", "short": "Moors"},
    13: {"original": "Transitional woodland, shrub", "short": "Transitional woodland"},
    14: {"original": "Beaches, dunes, sands", "short": "Sand"},
    15: {"original": "Inland wetlands", "short": "Wetlands"},
    16: {"original": "Coastal wetlands", "short": "Coastal"},
    17: {"original": "Inland waters", "short": "Waters"},
    18: {"original": "Marine waters", "short": "Marine"},
}
